import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'rescate_musical.settings')
django.setup()

from artistas.models import Artista

data = [
    {
        "nombre": "Salvador Bustamante Celi",
        "biografia": "Nació el 1 de marzo de 1876 en Loja. Es considerado uno de los músicos más importantes del país y una figura clave en el desarrollo de la música académica ecuatoriana.",
        "biografia_en": "Born on March 1, 1876, in Loja. He is considered one of the most important musicians in the country and a key figure in the development of Ecuadorian academic music.",
        "biografia_fr": "Né le 1er mars 1876 à Loja. Il est considéré comme l'un des musiciens les plus importants du pays et une figure clé du développement de la musique académique équatorienne.",
        "periodo_vida": "1 de marzo de 1876 – 1935",
        "periodo_vida_en": "March 1, 1876 – 1935",
        "periodo_vida_fr": "1er mars 1876 – 1935",
        "composiciones": "Más de 100 obras entre música religiosa, académica y popular",
        "composiciones_en": "More than 100 works among religious, academic and popular music",
        "composiciones_fr": "Plus de 100 œuvres parmi la musique religieuse, académique et populaire",
        "obras_destacadas": "Cantatas, villancicos, piezas sinfónicas",
        "obras_destacadas_en": "Cantatas, carols, symphonic pieces",
        "obras_destacadas_fr": "Cantates, chants de Noël, pièces symphoniques",
        "legado": "Sentó las bases de la música en Loja, formando generaciones de músicos.",
        "legado_en": "Layed the foundations of music in Loja, training generations of musicians.",
        "legado_fr": "A jeté les bases de la musique à Loja, formant des générations de musiciens."
    },
    {
        "nombre": "Segundo Cueva Celi",
        "biografia": "Nació el 10 de enero de 1901 en Loja. Maestro del pasillo ecuatoriano y compositor prolífico.",
        "biografia_en": "Born on January 10, 1901, in Loja. Master of the Ecuadorian pasillo and prolific composer.",
        "biografia_fr": "Né le 10 janvier 1901 à Loja. Maître du pasillo équatorien et compositeur prolifique.",
        "periodo_vida": "10 de enero de 1901 – 1969",
        "periodo_vida_en": "January 10, 1901 – 1969",
        "periodo_vida_fr": "10 janvier 1901 – 1969",
        "composiciones": "Cerca de 80 composiciones, mayoritariamente pasillos.",
        "composiciones_en": "About 80 compositions, mostly pasillos.",
        "composiciones_fr": "Environ 80 compositions, principalement des pasillos.",
        "obras_destacadas": "Pequeña ciudadana, Vaso de lágrimas.",
        "obras_destacadas_en": "Pequeña ciudadana, Vaso de lágrimas.",
        "obras_destacadas_fr": "Pequeña ciudadana, Vaso de lágrimas.",
        "legado": "Consolidó el pasillo lojano como referente cultural nacional.",
        "legado_en": "Consolidated the Loja pasillo as a national cultural reference.",
        "legado_fr": "A consolidé le pasillo de Loja comme référence culturelle nationale."
    },
    {
        "nombre": "Manuel de Jesús Lozano",
        "biografia": "Nacido a inicios del s. XX, Lozano fue pilar de la música tradicional en Loja.",
        "biografia_en": "Born in the early 20th century, Lozano was a pillar of traditional music in Loja.",
        "biografia_fr": "Né au début du XXe siècle, Lozano était un pilier de la musique traditionnelle à Loja.",
        "periodo_vida": "Principios s. XX",
        "periodo_vida_en": "Early 20th Century",
        "periodo_vida_fr": "Début du XXe siècle",
        "composiciones": "Extenso repertorio de música popular y pasillos.",
        "composiciones_en": "Extensive repertoire of popular music and pasillos.",
        "composiciones_fr": "Vaste répertoire de musique populaire et de pasillos.",
        "obras_destacadas": "Pasillos emblemáticos de la región.",
        "obras_destacadas_en": "Emblematic pasillos of the region.",
        "obras_destacadas_fr": "Pasillos emblématiques de la région.",
        "legado": "Perpetuó el estilo bohemio y romántico de Loja.",
        "legado_en": "Perpetuated the bohemian and romantic style of Loja.",
        "legado_fr": "A perpétué le style bohème et romantique de Loja."
    },
    {
        "nombre": "Marcos Ochoa Muñoz",
        "biografia": "Destacado por sus piezas instrumentales y aporte a la educación musical.",
        "biografia_en": "Highlighted for his instrumental pieces and contribution to music education.",
        "biografia_fr": "Reconnu pour ses pièces instrumentales et sa contribution à l'éducation musicale.",
        "periodo_vida": "Siglo XX",
        "periodo_vida_en": "20th Century",
        "periodo_vida_fr": "XXe siècle",
        "composiciones": "Música instrumental y popular.",
        "composiciones_en": "Instrumental and popular music.",
        "composiciones_fr": "Musique instrumentale et populaire.",
        "obras_destacadas": "Arreglos para bandas y orquestas.",
        "obras_destacadas_en": "Arrangements for bands and orchestras.",
        "obras_destacadas_fr": "Arrangements pour fanfares et orchestres.",
        "legado": "Fortaleció las bandas municipales y grupos locales.",
        "legado_en": "Strengthened municipal bands and local groups.",
        "legado_fr": "A renforcé les fanfares municipales et les groupes locaux."
    },
    {
        "nombre": "Emiliano Ortega",
        "biografia": "Hito cultural lojano, impulsor de las artes y las letras.",
        "biografia_en": "Loja cultural milestone, promoter of arts and letters.",
        "biografia_fr": "Jalon culturel de Loja, promoteur des arts et des lettres.",
        "periodo_vida": "1898 – 1971",
        "periodo_vida_en": "1898 – 1971",
        "periodo_vida_fr": "1898 – 1971",
        "composiciones": "Música versátil e inspirada en la literatura.",
        "composiciones_en": "Versatile music inspired by literature.",
        "composiciones_fr": "Musique polyvalente inspirée par la littérature.",
        "obras_destacadas": "Composiciones literarias convertidas en música.",
        "obras_destacadas_en": "Literary compositions turned into music.",
        "obras_destacadas_fr": "Compositions littéraires transformées en musique.",
        "legado": "Puente entre la poesía y la música lojana.",
        "legado_en": "Bridge between Loja poetry and music.",
        "legado_fr": "Pont entre la poésie et la musique de Loja."
    },
    {
        "nombre": "Víctor Moreno Proaño",
        "biografia": "Intérprete y compositor de notable trayectoria en el s. XX.",
        "biografia_en": "Performer and composer of notable career in the 20th century.",
        "biografia_fr": "Interprète et compositeur au parcours remarquable au XXe siècle.",
        "periodo_vida": "Siglo XX",
        "periodo_vida_en": "20th Century",
        "periodo_vida_fr": "XXe siècle",
        "composiciones": "Géneros tradicionales y piezas para instrumentos de cuerda.",
        "composiciones_en": "Traditional genres and pieces for string instruments.",
        "composiciones_fr": "Genres traditionnels et pièces pour instruments à cordes.",
        "obras_destacadas": "Interpretaciones magistrales de la música lojana.",
        "obras_destacadas_en": "Masterful interpretations of Loja music.",
        "obras_destacadas_fr": "Interprétations magistrales de la musique de Loja.",
        "legado": "Ferviente defensor de la autenticidad sonora de la región.",
        "legado_en": "Fervent defender of the region's sonic authenticity.",
        "legado_fr": "Défenseur fervent de l'authenticité sonore de la région."
    },
    {
        "nombre": "Daniel Armijos Carrión",
        "biografia": "Especialista en música para bandas y educación pública.",
        "biografia_en": "Specialist in band music and public education.",
        "biografia_fr": "Spécialiste de la musique pour fanfare et de l'éducation publique.",
        "periodo_vida": "Principios s. XX",
        "periodo_vida_en": "Early 20th Century",
        "periodo_vida_fr": "Début du XXe siècle",
        "composiciones": "Marchas, pasillos y arreglos corales.",
        "composiciones_en": "Marches, pasillos and choral arrangements.",
        "composiciones_fr": "Marches, pasillos et arrangements choraux.",
        "obras_destacadas": "Himnos locales y obras pedagógicas.",
        "obras_destacadas_en": "Local hymns and pedagogical works.",
        "obras_destacadas_fr": "Hymnes locaux et œuvres pédagogiques.",
        "legado": "Impulsó la creación de academias populares.",
        "legado_en": "Promoted the creation of popular academies.",
        "legado_fr": "A encouragé la création d'académies populaires."
    },
    {
        "nombre": "David Pacheco Ochoa",
        "biografia": "Virtuoso del violín y director de orquestas fundamentales.",
        "biografia_en": "Violin virtuoso and conductor of fundamental orchestras.",
        "biografia_fr": "Virtuose du violon et chef d'orchestres fondamentaux.",
        "periodo_vida": "1920 – 1978",
        "periodo_vida_en": "1920 – 1978",
        "periodo_vida_fr": "1920 – 1978",
        "composiciones": "Obras sinfónicas de gran calado.",
        "composiciones_en": "Symphonic works of great importance.",
        "composiciones_fr": "Œuvres symphoniques de grande importance.",
        "obras_destacadas": "Conciertos para violín y suites orquestales.",
        "obras_destacadas_en": "Violin concertos and orchestral suites.",
        "obras_destacadas_fr": "Concertos pour violon et suites orchestrales.",
        "legado": "Llevó la técnica académica lojana a estándares internacionales.",
        "legado_en": "Brought Loja academic technique to international standards.",
        "legado_fr": "A porté la technique académique de Loja aux standards internationaux."
    },
    {
        "nombre": "Julio Cañar",
        "biografia": "Pionero en la grabación y difusión del patrimonio sonoro.",
        "biografia_en": "Pioneer in recording and disseminating sonic heritage.",
        "biografia_fr": "Pionnier dans l'enregistrement et la diffusion du patrimoine sonore.",
        "periodo_vida": "Principios s. XX",
        "periodo_vida_en": "Early 20th Century",
        "periodo_vida_fr": "Début du XXe siècle",
        "composiciones": "Recopilaciones y creaciones de música vernácula.",
        "composiciones_en": "Compilations and creations of vernacular music.",
        "composiciones_fr": "Compilations et créations de musique vernaculaire.",
        "obras_destacadas": "Registros históricos en vinilo y casete.",
        "obras_destacadas_en": "Historical records on vinyl and cassette.",
        "obras_destacadas_fr": "Enregistrements historiques sur vinyle et cassette.",
        "legado": "Permitió que la música lojana sobreviviera en el registro digital.",
        "legado_en": "Allowed Loja music to survive in the digital record.",
        "legado_fr": "A permis à la musique de Loja de survivre dans les archives numériques."
    },
    {
        "nombre": "Francisco Rodas Bustamante",
        "biografia": "Maestro de capilla y figura central en la música sacra colonial tardía.",
        "biografia_en": "Choirmaster and central figure in late colonial sacred music.",
        "biografia_fr": "Maître de chapelle et figure centrale de la musique sacrée coloniale tardive.",
        "periodo_vida": "Siglo XIX",
        "periodo_vida_en": "19th Century",
        "periodo_vida_fr": "XIXe siècle",
        "composiciones": "Misas, villancicos barrocos y cantatas.",
        "composiciones_en": "Masses, baroque carols and cantatas.",
        "composiciones_fr": "Messes, chants de Noël baroques et cantates.",
        "obras_destacadas": "Archivo de música sacra de la Diócesis de Loja.",
        "obras_destacadas_en": "Sacred music archive of the Diocese of Loja.",
        "obras_destacadas_fr": "Archives de musique sacrée du diocèse de Loja.",
        "legado": "Preservó la notación musical histórica de Loja.",
        "legado_en": "Preserved Loja's historical musical notation.",
        "legado_fr": "A préservé la notation musicale historique de Loja."
    }
]

for item in data:
    # Update only the translation fields and biography content
    Artista.objects.update_or_create(
        nombre=item["nombre"],
        defaults={
            "biografia": item["biografia"],
            "biografia_en": item["biografia_en"],
            "biografia_fr": item["biografia_fr"],
            "periodo_vida": item["periodo_vida"],
            "periodo_vida_en": item["periodo_vida_en"],
            "periodo_vida_fr": item["periodo_vida_fr"],
            "composiciones_resumen": item["composiciones"],
            "composiciones_resumen_en": item["composiciones_en"],
            "composiciones_resumen_fr": item["composiciones_fr"],
            "obras_destacadas_resumen": item["obras_destacadas"],
            "obras_destacadas_resumen_en": item["obras_destacadas_en"],
            "obras_destacadas_resumen_fr": item["obras_destacadas_fr"],
            "legado_resumen": item["legado"],
            "legado_resumen_en": item["legado_en"],
            "legado_resumen_fr": item["legado_fr"],
        }
    )
    print(f"Updated: {item['nombre']}")

print("Full multilingual biographies updated.")
