# Generated by Django 6.0.3 on 2026-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_artista_composiciones_resumen_artista_legado_resumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='biografia_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='biografia_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='composiciones_resumen_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='composiciones_resumen_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='legado_resumen_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='legado_resumen_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='obras_destacadas_resumen_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='obras_destacadas_resumen_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='periodo_vida_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artista',
            name='periodo_vida_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hitolineatiempo',
            name='evento_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hitolineatiempo',
            name='evento_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='obradestacada',
            name='descripcion_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obradestacada',
            name='descripcion_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obradestacada',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='obradestacada',
            name='titulo_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
