# Generated by Django 6.0.3 on 2026-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacion', '0002_resultadoquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='descripcion_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='descripcion_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='logro',
            name='nombre_fr',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='opcion',
            name='texto_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='opcion',
            name='texto_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto_pregunta_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='texto_pregunta_fr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quiz',
            name='descripcion_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='descripcion_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='titulo_fr',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
